# Custom rubocop configuration

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - deepl-rb.gemspec
    - vendor/**/*

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/ParameterLists:
  Max: 6

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self
